name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: 'Mona'
  use-output:
    runs-on: ubuntu-latest
    needs: [call-reusable-workflow]
    steps:
      - run: echo "The time was ${{ needs.call-reusable-workflow.outputs.current-time }}"
